### ISSUE TITLE
Error: Endomondo Error: User id is not defined

### ISSUE THREAD

**Issue by blazejhanzel** [fabulator/endomondo-api-handler#21]
Terminal display this error after running script:

`(node:436) UnhandledPromiseRejectionWarning: Error: Endomondo Error: User id is not defined
    at Api.getUserApiUrl (/Desktop/node_modules/endomondo-api-handler/dist/index.js:942:13)
    at Api.getWorkoutsApiUrl (/Desktop/node_modules/endomondo-api-handler/dist/index.js:953:17)
    at Api.getWorkouts (/Desktop/node_modules/endomondo-api-handler/dist/index.js:1056:42)
    at Api.processWorkouts (/Desktop/node_modules/endomondo-api-handler/dist/index.js:1084:29)
    at /Desktop/endomondo.js:10:15
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

There is no problem (with this; I get other errors with workout) when I write profile id manually in 938 line of index.js

**Comment by fabulator** [comment]
I made a mistake in setting default user id. It's fixed in v2.0.1
