### ISSUE TITLE
Can not download all my workouts gpx'es - Uncaught REST API exception on all GPX workouts export

### ISSUE THREAD

**Issue by kosmalaa** [fabulator/endomondo-api-handler#278]
Can not download all my workouts gpx'es

`index.js`
```
require('cross-fetch/polyfill');
const fs = require('fs');
const { Api } = require('endomondo-api-handler');

const api = new Api();

(async () => {
    await api.login("{username}","{password}");

    await api.processWorkouts({}, async (workout) => {
        console.log(workout.toString());
        if (workout.hasGPSData()) {
            fs.writeFileSync(`tmp/${workout.getId()}.gpx`, await api.getWorkoutGpx(workout.getId()), 'utf8');
        }
    });
})();
```
`error`
```> node index.js
/Users/arek/IdeaProjects/export-endomondo/node_modules/.pnpm/rest-api-handler@2.20.0/node_modules/rest-api-handler/dist/index.js:358
      throw new this.Exception(toRespond, request);
            ^

EndomondoApiException [Error]: Endomondo Error: "Uncaught REST API exception:\nURL: http://www.endomondo.com/rest/v1/users/{userId}/workouts/history\nMethod: GET\nParameters: {expand=[points,workout]}\n"
    at DefaultResponseProcessor.processResponse (/Users/arek/IdeaProjects/export-endomondo/node_modules/.pnpm/rest-api-handler@2.20.0/node_modules/rest-api-handler/dist/index.js:358:13)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async resolveProcessors (/Users/arek/IdeaProjects/export-endomondo/node_modules/.pnpm/rest-api-handler@2.20.0/node_modules/rest-api-handler/dist/index.js:27:100)
    at async Api.getWorkouts (/Users/arek/IdeaProjects/export-endomondo/node_modules/.pnpm/endomondo-api-handler@7.3.52/node_modules/endomondo-api-handler/dist/api/Api.js:192:22)
    at async Api.processWorkouts (/Users/arek/IdeaProjects/export-endomondo/node_modules/.pnpm/endomondo-api-handler@7.3.52/node_modules/endomondo-api-handler/dist/api/Api.js:215:9)
    at async /Users/arek/IdeaProjects/export-endomondo/index.js:10:5 {
  response: {
    data: 'Uncaught REST API exception:\n' +
      'URL: http://www.endomondo.com/rest/v1/users/{userId}/workouts/history\n' +
      'Method: GET\n' +
      'Parameters: {expand=[points,workout]}\n',
    status: 500,
    source: Response {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: {
        body: PassThrough {
          _readableState: ReadableState {
            objectMode: false,
            highWaterMark: 16384,
            buffer: [BufferList],
            length: 0,
            pipes: [],
            flowing: true,
            ended: true,
            endEmitted: true,
            reading: false,
            constructed: true,
            sync: false,
            needReadable: false,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            errorEmitted: false,
            emitClose: true,
            autoDestroy: true,
            destroyed: true,
            errored: null,
            closed: true,
            closeEmitted: true,
            defaultEncoding: 'utf8',
            awaitDrainWriters: null,
            multiAwaitDrain: false,
            readingMore: false,
            decoder: null,
            encoding: null,
            [Symbol(kPaused)]: false
          },
          _events: [Object: null prototype] {
            prefinish: [Function: prefinish],
            error: [Array],
            data: [Function (anonymous)],
            end: [Function (anonymous)]
          },
          _eventsCount: 4,
          _maxListeners: undefined,
          _writableState: WritableState {
            objectMode: false,
            highWaterMark: 16384,
            finalCalled: true,
            needDrain: false,
            ending: true,
            ended: true,
            finished: true,
            destroyed: true,
            decodeStrings: true,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [Function: bound onwrite],
            writecb: null,
            writelen: 0,
            afterWriteTickInfo: null,
            buffered: [],
            bufferedIndex: 0,
            allBuffers: true,
            allNoop: true,
            pendingcb: 0,
            constructed: true,
            prefinished: true,
            errorEmitted: false,
            emitClose: true,
            autoDestroy: true,
            errored: null,
            closed: true,
            closeEmitted: true,
            [Symbol(kOnFinished)]: []
          },
          allowHalfOpen: true,
          [Symbol(kCapture)]: false,
          [Symbol(kCallback)]: null
        },
        disturbed: true,
        error: null
      },
      [Symbol(Response internals)]: {
        url: 'https://www.endomondo.com/rest/v1/users/{userId}/workouts/history?expand=points%2Cworkout',
        status: 500,
        statusText: 'Internal Server Error',
        headers: Headers {
          [Symbol(map)]: [Object: null prototype] {
            'content-type': [Array],
            'content-length': [Array],
            connection: [Array],
            'cache-control': [Array],
            date: [Array],
            server: [Array],
            'x-cache': [Array],
            via: [Array],
            'x-amz-cf-pop': [Array],
            'x-amz-cf-id': [Array]
          }
        },
        counter: 0
      }
    },
    request: Request {
      size: 0,
      timeout: 0,
      follow: 20,
      compress: true,
      counter: 0,
      agent: undefined,
      [Symbol(Body internals)]: { body: null, disturbed: false, error: null },
      [Symbol(Request internals)]: {
        method: 'GET',
        redirect: 'follow',
        headers: Headers {
          [Symbol(map)]: [Object: null prototype] {
            'content-type': [Array],
            'x-csrf-token': [Array],
            cookie: [Array]
          }
        },
        parsedURL: Url {
          protocol: 'https:',
          slashes: true,
          auth: null,
          host: 'www.endomondo.com',
          port: null,
          hostname: 'www.endomondo.com',
          hash: null,
          search: '?expand=points%2Cworkout',
          query: 'expand=points%2Cworkout',
          pathname: '/rest/v1/users/{userId}/workouts/history',
          path: '/rest/v1/users/{userId}/workouts/history?expand=points%2Cworkout',
          href: 'https://www.endomondo.com/rest/v1/users/{userId}/workouts/history?expand=points%2Cworkout'
        },
        signal: null
      }
    }
  }
}
 ERROR  Command failed with exit code 1.
```

Looks like `https://www.endomondo.com/rest/v1/users/{userId}/workouts/history?expand=points%2Cworkout` call is a problem.
```
Uncaught REST API exception:
URL: http://www.endomondo.com/rest/v1/users/{userId}/workouts/history
Method: GET
Parameters: {expand=[points,workout]}
```

**Comment by samriley** [comment]
I think the issue is that the endomondo api sometimes returns a error. I worked around this by wrapping fetch with some retry logic using `fetch-retry`. As to if the API errors should be handled in this package or left to implementers to do I'll leave to the maintainers to decide.

Replace
```
require('cross-fetch/polyfill');
```

With 
```
const crossFetch = require('cross-fetch');
global.fetch = require('fetch-retry')(crossFetch);
global.Response = crossFetch.Response
global.Headers = crossFetch.Headers
global.Request = crossFetch.Request
```
